$('.b1').on("click", function(){
    $("body").css('backgroundColor','#F2AFEF')
    $("h1").css('color','black')
    $(".b1").animate({
        height:'150px',
        width:'150px'
    },"slow")
    $(".b2").animate({
        height:'150px',
        width:'50px'
    },"slow")
    $(".b3").animate({
        height:'50px',
        width:'150px'
    },"slow")
    $(".b4").animate({
        height:'50px',
        width:'50px'
    },"slow")
})
$('.b2').on("click", function(){
    $("body").css('backgroundColor','#FF004D')
    $("h1").css('color','white')
    $(".b1").animate({
        height:'150px',
        width:'50px'
    },"slow")
    $(".b2").animate({
        height:'150px',
        width:'150px'
    },"slow")
    $(".b3").animate({
        height:'50px',
        width:'50px'
    },"slow")
    $(".b4").animate({
        height:'50px',
        width:'150px'
    },"slow")
})
$('.b3').on("click", function(){
    $("body").css('backgroundColor','#864AF9')
    $("h1").css('color','white')
    $(".b1").animate({
        height:'50px',
        width:'150px'
    },"slow")
    $(".b2").animate({
        height:'50px',
        width:'50px'
    },"slow")
    $(".b3").animate({
        height:'150px',
        width:'150px'
    },"slow")
    $(".b4").animate({
        height:'150px',
        width:'50px'
    },"slow")
})
$('.b4').on("click", function(){
    $("body").css('backgroundColor','#F8E559')
    $("h1").css('color','black')
    $(".b1").animate({
        height:'50px',
        width:'50px'
    },"slow")
    $(".b2").animate({
        height:'50px',
        width:'150px'
    },"slow")
    $(".b3").animate({
        height:'150px',
        width:'50px'
    },"slow")
    $(".b4").animate({
        height:'150px',
        width:'150px'
    },"slow")
})
$("button").on("click",function(){
    $("button").animate({
        height:'100px',
        width:'100px'
    },1500)
})